---
- name: Ask the LLM a question, get feedback on the answer
  hosts: localhost
  gather_facts: no
  vars:
    profile: default
  vars_prompt:
    - name: question
      prompt: "Enter a question for the LLM:"
      private: false
  tasks:
    - name: Ask question
      lwe:
        message: "{{ question }}"
        profile: "{{ profile }}"
      register: answer
    - name: Display answer
      debug:
        var: answer.response
    - name: Critical feedback
      lwe:
        message: "Given this question: {{ question }}\n\n Provide critical feedback on this answer to the question: {{ answer.response }}\n\nIn the feedback, include at least three recommendations that can be incorporated to improve the answer."
        profile: "{{ profile }}"
      register: feedback
    - name: Display feedback
      debug:
        var: feedback.response
    - name: New answer after feedback
      lwe:
        message: "Given this question: {{ question }}\n\nGiven this answer to the question: {{ answer.response }}\n\nGiven this feedback on the answer to the question: {{ feedback.response }}\n\nProvide a new answer to the question that incorporates the feedback"
        profile: "{{ profile }}"
      register: answer_after_feedback
    - name: Display new answer after feedback
      debug:
        var: answer_after_feedback.response
