---
# Ask a question to the LLM, get an answer
#
# Illustrates prompting the user for information before running the workflow.
- name: Ask the LLM a question
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: question
      prompt: "Enter a question for the LLM"
      private: false
  tasks:
    - name: "Ask question: {{ question }}"
      lwe_llm:
        message: "{{ question }}"
      register: result
    - name: Display response
      debug:
        var: result
