---
- name: Ask the LLM a question
  hosts: localhost
  gather_facts: no
  vars:
    model: gpt-3.5-turbo
    temperature: 0.7
  vars_prompt:
    - name: question
      prompt: "Enter a question for the LLM:"
      private: false
  tasks:
    - name: Ask question
      lwe:
        message: "{{ question }}"
      register: result
    - name: Display response
      debug:
        var: result.response
